configuration: Release
image: Visual Studio 2017

environment:
  PRODUCT_NAME: RombSkeleton
  sonar_login:
    secure: +fPGU8/Ueb05tX4cbo3EoLSMmS2EW0Ln0TtxKSHUo55LrJMvyvE2CqK7dRcGtL01
  secret_for_snk:
    secure: 9wAuC5ZEdGrfCqltk4Ax6Q==
  COVERALLS_REPO_TOKEN:
    secure: C5rzrcxa1tpwN/APHa/93zFZpxAtnj0aol81DhY0w78cyn+Aj1kUIMbwSAG6B+jx

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '$(GitVersion_AssemblySemVer)'
  file_version: '$(GitVersion_AssemblySemVer)'
  informational_version: '{version}'

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(GitVersion_AssemblySemVer)'
  assembly_file_version: '$(GitVersion_AssemblySemVer)'
  assembly_informational_version: '{version}'

cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  
install:
  - choco install gitversion.portable -pre -y
  - choco install resharper-clt -y
  - choco install "msbuild-sonarqube-runner" -y
  - nuget install secure-file -ExcludeVersion
  - nuget install OpenCover -ExcludeVersion
  - nuget install coveralls.net -ExcludeVersion
  - secure-file\tools\secure-file -decrypt %APPVEYOR_BUILD_FOLDER%\tools\Key\Key.snk.enc -secret %secret_for_snk%  
  - gitversion /l console /output buildserver

before_build:
  - ps: dotnet restore src\$env:PRODUCT_NAME.sln
  - MSBuild.SonarQube.Runner.exe begin /k:"rombolshak:%PRODUCT_NAME%" /n:"%PRODUCT_NAME%" /v:%APPVEYOR_BUILD_VERSION% /d:sonar.host.url=https://sonarqube.com /d:sonar.login=%sonar_login%

build_script:
  - ps: dotnet build src\$env:PRODUCT_NAME.sln

after_build:
  - ps: inspectcode.exe /o:tools\Build\ReSharperRules\ListOfIssues.xml src\$env:PRODUCT_NAME.sln
  - ps: tools\Build\ReSharperRules\OutputAnalyzeFilter.ps1
  - ps: tools\Build\ReSharperRules\ProblemsChecker.ps1 -pathToFilteredXml tools\Build\ReSharperRules\FilteredListOfIssues.xml

test_script:
  - OpenCover\tools\OpenCover.Console.exe -target:powershell.exe -targetargs:%APPVEYOR_BUILD_FOLDER%\tools\xunit_test.ps1 -filter:"+[*]* -[*.Tests]*" -register:user -returntargetcode 
  
after_test:
  - coveralls.net\tools\csmacnz.Coveralls.exe --opencover -i .\results.xml
  #- ps: $wc = New-Object 'System.Net.WebClient'; $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
  - MSBuild.SonarQube.Runner.exe end /d:sonar.login=%sonar_login%
  
artifacts:
  - path: bin\Release
